# Generated by Django 6.1 on 2026-09-14 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_achievement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='category',
            field=models.CharField(choices=[('perlombaan', 'Perlombaan'), ('penelitian', 'Penelitian'), ('lainnya', 'Others')], default='perlombaan', max_length=20),
        ),
    ]
